# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fe309e0b427c5139644a0c5190f14116c661663557e6679d4484af5e41200518d03b67c1a4627af7b4a79be8437e8286980b25555eac5956355d0c86ca44cb8

test:
  secret_key_base: 5ff8dd93f0d16b5a8f1239c94272b38ed0341ccfc61be2af7653cdd4309161befc5baec89622abe4d04633460cf8daf1a6a6f4f19851d136ed3c561532d42678

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
